saved/config/routes.rb
Saved::Application.routes.draw do
  resources :subreddits

  resources :users

  resources :posts

end

saved/app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_indexed :fields => [:title, :author,:subreddit,:domain]
end

saved/app/models/subreddit.rb
class Subreddit < ActiveRecord::Base
end

saved/app/models/user.rb
class User < ActiveRecord::Base
end

saved/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

saved/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.with_query(params[:search]).paginate(
      :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

saved/app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController
  # GET /subreddits
  # GET /subreddits.json
  def index
    @subreddits = Subreddit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subreddits }
    end
  end

  # GET /subreddits/1
  # GET /subreddits/1.json
  def show
    @subreddit = Subreddit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subreddit }
    end
  end

  # GET /subreddits/new
  # GET /subreddits/new.json
  def new
    @subreddit = Subreddit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subreddit }
    end
  end

  # GET /subreddits/1/edit
  def edit
    @subreddit = Subreddit.find(params[:id])
  end

  # POST /subreddits
  # POST /subreddits.json
  def create
    @subreddit = Subreddit.new(params[:subreddit])

    respond_to do |format|
      if @subreddit.save
        format.html { redirect_to @subreddit, notice: 'Subreddit was successfully created.' }
        format.json { render json: @subreddit, status: :created, location: @subreddit }
      else
        format.html { render action: "new" }
        format.json { render json: @subreddit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subreddits/1
  # PUT /subreddits/1.json
  def update
    @subreddit = Subreddit.find(params[:id])

    respond_to do |format|
      if @subreddit.update_attributes(params[:subreddit])
        format.html { redirect_to @subreddit, notice: 'Subreddit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subreddit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subreddits/1
  # DELETE /subreddits/1.json
  def destroy
    @subreddit = Subreddit.find(params[:id])
    @subreddit.destroy

    respond_to do |format|
      format.html { redirect_to subreddits_url }
      format.json { head :no_content }
    end
  end
end

saved/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

saved/app/helpers/application_helper.rb
module ApplicationHelper
end

saved/app/helpers/posts_helper.rb
module PostsHelper
end

saved/app/helpers/subreddits_helper.rb
module SubredditsHelper
end

saved/app/helpers/users_helper.rb
module UsersHelper
end

saved/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Saved</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

saved/app/views/posts/_form.html.haml
= form_for @post do |f|
  -if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :selftext_html
    = f.text_field :selftext_html
  .field
    = f.label :selftext
    = f.text_field :selftext
  .field
    = f.label :author
    = f.text_field :author
  .field
    = f.label :subreddit
    = f.text_field :subreddit
  .field
    = f.label :permalink
    = f.text_field :permalink
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :domain
    = f.text_field :domain
  .field
    = f.label :created_utc
    = f.date_select :created_utc
  .field
    = f.label :num_comments
    = f.number_field :num_comments
  .field
    = f.label :likes
    = f.check_box :likes
  .field
    = f.label :ups
    = f.number_field :ups
  .field
    = f.label :downs
    = f.number_field :downs
  .field
    = f.label :score
    = f.number_field :score
  .field
    = f.label :over_18
    = f.check_box :over_18
  .field
    = f.label :is_self
    = f.check_box :is_self
  .actions
    = f.submit 'Save'

saved/app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

saved/app/views/posts/index.html.haml
%h1 Listing posts
=form_tag posts_path, :method => 'get' do
  = text_field_tag :search, params[:search]
  = submit_tag "Search", :name => nil

%table
  %tr
    %th Title
    %th Selftext html
    %th Selftext
    %th Author
    %th Subreddit
    %th Permalink
    %th Url
    %th Domain
    %th Created utc
    %th Num comments
    %th Likes
    %th Ups
    %th Downs
    %th Score
    %th Over 18
    %th Is self
    %th
    %th
    %th

  - @posts.each do |post|
    %tr
      %td= post.title
      %td= post.selftext_html
      %td= post.selftext
      %td= post.author
      %td= post.subreddit
      %td= link_to post.permalink,"http://www.reddit.com#{post.permalink}"
      %td= link_to post.url,post.url
      %td= post.domain
      %td= post.created_utc
      %td= post.num_comments
      %td= post.likes
      %td= post.ups
      %td= post.downs
      %td= post.score
      %td= post.over_18
      %td= post.is_self
      %td= link_to 'Show', post
      %td= link_to 'Edit', edit_post_path(post)
      %td= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete

%br
= will_paginate @posts
= link_to 'New Post', new_post_path

saved/app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

saved/app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @post.title
%p
  %b Name:
  = @post.name
%p
  %b Selftext html:
  = @post.selftext_html
%p
  %b Selftext:
  = @post.selftext
%p
  %b Author:
  = @post.author
%p
  %b Subreddit:
  = @post.subreddit
%p
  %b Permalink:
  = @post.permalink
%p
  %b Url:
  = @post.url
%p
  %b Domain:
  = @post.domain
%p
  %b Created utc:
  = @post.created_utc
%p
  %b Num comments:
  = @post.num_comments
%p
  %b Likes:
  = @post.likes
%p
  %b Ups:
  = @post.ups
%p
  %b Downs:
  = @post.downs
%p
  %b Score:
  = @post.score
%p
  %b Over 18:
  = @post.over_18
%p
  %b Is self:
  = @post.is_self

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

saved/app/views/subreddits/_form.html.haml
= form_for @subreddit do |f|
  -if @subreddit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subreddit.errors.count, "error")} prohibited this subreddit from being saved:"
      %ul
        - @subreddit.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :subreddit_id
    = f.text_field :subreddit_id
  .actions
    = f.submit 'Save'

saved/app/views/subreddits/edit.html.haml
%h1 Editing subreddit

= render 'form'

= link_to 'Show', @subreddit
\|
= link_to 'Back', subreddits_path

saved/app/views/subreddits/index.html.haml
%h1 Listing subreddits

%table
  %tr
    %th Name
    %th Subreddit
    %th
    %th
    %th

  - @subreddits.each do |subreddit|
    %tr
      %td= subreddit.name
      %td= subreddit.subreddit_id
      %td= link_to 'Show', subreddit
      %td= link_to 'Edit', edit_subreddit_path(subreddit)
      %td= link_to 'Destroy', subreddit, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Subreddit', new_subreddit_path

saved/app/views/subreddits/new.html.haml
%h1 New subreddit

= render 'form'

= link_to 'Back', subreddits_path

saved/app/views/subreddits/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @subreddit.name
%p
  %b Subreddit:
  = @subreddit.subreddit_id

= link_to 'Edit', edit_subreddit_path(@subreddit)
\|
= link_to 'Back', subreddits_path

saved/app/views/users/_form.html.haml
= form_for @user do |f|
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

saved/app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

saved/app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New User', new_user_path

saved/app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

saved/app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path